


--CRIAR BANCO DE DADOS AULA2407
USE master
GO
IF EXISTS (SELECT name FROM sys.databases WHERE name = 'AULA2407')
BEGIN
    PRINT 'BANCO JÁ EXISTE AULA2407'
END
ELSE
BEGIN
CREATE DATABASE AULA2407
	PRINT 'BANCO CRIADO AULA2407.'
END
GO
 
USE AULA2407
GO
 
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'CLIENTES')
BEGIN
    PRINT 'TABELA JÁ EXISTE.'
END
ELSE
BEGIN
	CREATE TABLE CLIENTES(
	Id INT IDENTITY,
	Nome NVARCHAR(MAX),
	CPF NVARCHAR(MAX),
	RG NVARCHAR(MAX),
	Usuario NVARCHAR(MAX),
	Senha NVARCHAR(MAX),
	CEP NVARCHAR(MAX),
	UF NVARCHAR(MAX),
	Cidade NVARCHAR(MAX),
	Bairro NVARCHAR(MAX),
	Rua NVARCHAR(MAX),
	Numero NVARCHAR(MAX),
	Complemento NVARCHAR(MAX)
	CONSTRAINT PKCLIENTES PRIMARY KEY (Id)
	)
    PRINT 'TABELA CLIENTES CRIADA'
END
GO
 
--SELECT * FROM CLIENTES

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'PRODUTOS')
BEGIN
    PRINT 'TABELA JÁ EXISTE.'
END
ELSE
BEGIN
	CREATE TABLE PRODUTOS(
	Id INT IDENTITY,
	Nome NVARCHAR(MAX),
	Fabricante NVARCHAR(MAX),
	Codigo INT,
	Quantidade INT,
	ValordeCompra DECIMAL,
	ValordeVenda DECIMAL,
	Descricao NVARCHAR(MAX),

	CONSTRAINT PKPRODUTOS PRIMARY KEY (Id)
	)
    PRINT 'TABELA PRODUTOS CRIADA'
END

--SELECT * FROM PRODUTOS

insert into PRODUTOS VALUES ('CAJU','NISSIN',12,5,10,20,'ruim')


SELECT * FROM PRODUTOS;
SELECT * FROM CLIENTES;